-- MySQL Script generated by MySQL Workbench
-- Fri Nov 15 16:22:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fastevent
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fastevent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fastevent` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fastevent` ;

-- -----------------------------------------------------
-- Table `fastevent`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastevent`.`user` ;

CREATE TABLE IF NOT EXISTS `fastevent`.`user` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Cognome` VARCHAR(255) NOT NULL,
  `Nascita` DATE NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fastevent`.`promoter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastevent`.`promoter` ;

CREATE TABLE IF NOT EXISTS `fastevent`.`promoter` (
  `PromoterID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Cognome` VARCHAR(255) NOT NULL,
  `Nascita` DATE NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`PromoterID`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `PromoterID_UNIQUE` (`PromoterID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fastevent`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastevent`.`event` ;

CREATE TABLE IF NOT EXISTS `fastevent`.`event` (
  `EventID` INT NOT NULL AUTO_INCREMENT,
  `Titolo` VARCHAR(255) NOT NULL,
  `nro_posti` INT NOT NULL,
  `Luogo` VARCHAR(255) NOT NULL,
  `Data` DATE NOT NULL,
  `promoter` INT NOT NULL,
  `Descrizione` VARCHAR(255) NOT NULL,
  `Genere` VARCHAR(255) NOT NULL,
  `isEcologic` TINYINT(1) NOT NULL,
  PRIMARY KEY (`EventID`),
  UNIQUE INDEX `EventID_UNIQUE` (`EventID` ASC) VISIBLE,
  INDEX `promoter` (`promoter` ASC) VISIBLE,
  CONSTRAINT `event_ibfk_1`
    FOREIGN KEY (`promoter`)
    REFERENCES `fastevent`.`promoter` (`PromoterID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fastevent`.`prezzo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastevent`.`prezzo` ;

CREATE TABLE IF NOT EXISTS `fastevent`.`prezzo` (
  `PriceID` INT NOT NULL AUTO_INCREMENT,
  `EventID` INT NOT NULL,
  `Titolo` VARCHAR(255) NOT NULL,
  `Descrizione` VARCHAR(255) NOT NULL,
  `Prezzo` DOUBLE(10,2) NOT NULL,
  PRIMARY KEY (`PriceID`),
  UNIQUE INDEX `PriceID_UNIQUE` (`PriceID` ASC) VISIBLE,
  INDEX `EventID` (`EventID` ASC) VISIBLE,
  CONSTRAINT `prezzo_ibfk_1`
    FOREIGN KEY (`EventID`)
    REFERENCES `fastevent`.`event` (`EventID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fastevent`.`acquista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastevent`.`acquista` ;

CREATE TABLE IF NOT EXISTS `fastevent`.`acquista` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `EventID` INT NOT NULL,
  `nro_ticket` INT NOT NULL,
  `PriceID` INT NOT NULL,
  `data_acquisto` DATE NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `UserID` (`UserID` ASC) VISIBLE,
  INDEX `EventID` (`EventID` ASC) VISIBLE,
  INDEX `PriceID` (`PriceID` ASC) VISIBLE,
  CONSTRAINT `acquista_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `fastevent`.`user` (`UserID`),
  CONSTRAINT `acquista_ibfk_2`
    FOREIGN KEY (`EventID`)
    REFERENCES `fastevent`.`event` (`EventID`),
  CONSTRAINT `acquista_ibfk_3`
    FOREIGN KEY (`PriceID`)
    REFERENCES `fastevent`.`prezzo` (`PriceID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fastevent`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fastevent`.`ticket` ;

CREATE TABLE IF NOT EXISTS `fastevent`.`ticket` (
  `TicketID` INT NOT NULL AUTO_INCREMENT,
  `EventID` INT NOT NULL,
  `Matricola` INT NOT NULL,
  `isScanned` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`TicketID`),
  UNIQUE INDEX `TicketID_UNIQUE` (`TicketID` ASC) VISIBLE,
  INDEX `EventID` (`EventID` ASC) VISIBLE,
  CONSTRAINT `ticket_ibfk_1`
    FOREIGN KEY (`EventID`)
    REFERENCES `fastevent`.`event` (`EventID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
